### ISSUE TITLE
Don't encourage users to bypass sudo

### ISSUE THREAD

**Issue by szhu** [tjluoma/fix-hostname#1]
A better alternative would be to have users install the launch item as a LaunchDaemon, instead of a LaunchAgent. LaunchDaemons always run as root. To change a LaunchAgent into a LaunchDaemon, simply move it to `/Library/LaunchDaemons`. There is no per-user LaunchDaemons folder, for obvious reasons.

**Comment by tjluoma** [comment]
I'm not particularly worried about adding the specific `scutil` command to the `sudoers` file because any admin user can make that change via System Preferences anyway, but using LaunchDaemons is a good idea because it can run even if no one is logged in, and it is easier than having to edit the `sudoers` file.

The only potential downside is that the entire script then runs as `root`, which may seem like a bigger risk to some people.

I've added instructions for installing it that way, and updated the script to check to see if it is being run as root and only using `sudo` if necessary.

Thanks for the feedback. I agree it's a better idea, even if I agree for different reasons :-)

**Comment by szhu** [comment]
> I'm not particularly worried about adding the specific `scutil` command to the `sudoers` file because any admin user can make that change via System Preferences anyway

Please describe how.

**Comment by tjluoma** [comment]
By going to the System Preferences panel for “Sharing” and changing the “Computer Name”

**Comment by szhu** [comment]
I present to you an analogous but obviously flawed argument:
_"Since any admin can delete apps without extra authentication, we can add `rm` to `sudoers`."_

What's wrong with this argument (and yours)?
1. `rm` can do more dangerous things that just deleting apps! (And `scutil` can do more dangerous things than what your script requires. Even if you think it can't, the burden is on you to prove so, since you would potentially be making users' systems more vulnerable.)
   
   But hey, I can actually show the existence of one vulnerability: Adding `scutil` to `sudoers` makes it possible to for a malicious agent to change the hostname to _anything_, not just the according to the rules of your script. Note that the functionality of your script is more limited than than of `scutil`.
2. This may make it possible for non-admins to delete apps, or worse, run `sudo rm` (and `sudo scutil`) as well.

Also, another reason for not keeping this in the home folder is that the effects of the script are not per-user but rather system-wide. Mac OS does a good job of separating domains into `~`, `/`, and `/System`, and it would be nice to respect that separation to avoid confusion.

**Comment by szhu** [comment]
> If you use that option, make sure that no one else can edit the `fix-hostname.sh` script, or they will be able to run commands as root.

This is a very important concern indeed. One way to mitigate this is to place the script contents inside the launch item instead of having them in a separate file. Having everything inside the plist is a good idea because [`launchd` will refuse to run LaunchDaemons whose plist files are editable by anyone other than root](http://apple.stackexchange.com/q/3250).

How do you you put the script contents inside the launch item? Note that `zsh -c 'command'` runs that command. You should edit the plist in Xcode/Property List Editor and set the contents to look roughly like:
- Arguments:
  
  ```
  zsh
  ```
  
  ```
  -c
  ```
  
  ``` sh
  NAME="$0:t:r"
  
  LOCAL_HOST_NAME=`/usr/sbin/scutil --get LocalHostName`
  
  ...  # paste entire script here
  ```

Note that you'll actually be able to place the entire script contents, including newlines, into the third argument.

**Comment by tjluoma** [comment]
I'm going to ignore the `rm` thing because it's far too specious and absurd. Anything `scutil` can do, an admin user can do via System Preferences. For the vast majority of Mac users who are the only users of their Mac, putting `scutil` into `sudoers` is more of a hassle than a threat. Quite frankly they are more likely to run into a problem with the syntax than a malicious script.

That being said, I agree that putting it into LaunchDaemons is a better idea, and the instructions are in there for doing just that.

**Comment by szhu** [comment]
Hm, that makes sense. Thanks!
